### ISSUE TITLE
Изменить README

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFSD-2UI#1]
Добавить README с описанием проекта и командами запуска. В нём добавить ссылки на github pages.

**Comment by rustho** [comment]
well done

**Comment by Maksimus-Prime** [comment]
Открой ишью, еще есть косяки:
Нет команды для сборки проекта, нужно добавить соответствующие скрипт

**Comment by rustho** [comment]
Не ну если надо - держи, ок.

**Comment by Maksimus-Prime** [comment]
Можешь закрывать)
