### ISSUE TITLE
Неверно работает ripple эффект

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFSD-2UI#12]
RIpple эффект должен находится над кнопкой, а не внутри неё
![ukngp_croper_ru](https://user-images.githubusercontent.com/26929933/32208345-87a09598-be34-11e7-8403-bb3f7ee28497.png)

**Comment by rustho** [comment]
воу воу воу, там не видно совсем на макете что она сверху

**Comment by Zarwlar** [comment]
Хотя да, там кто как видит. Но в любом случае рипл должен быть белым
