### ISSUE TITLE
В stylus не использовать : ;

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFSD-2UI#16]
По сути дела, это визуальный шум и без него стили будут выглядеть чище

**Comment by rustho** [comment]
я наоборот теряюсь когда не нахожу двоеточий и точки с запятой... поэтому оставляю

**Comment by Zarwlar** [comment]
В принципе, это не очень критично, но на рабочих проектах они не используются. Поэтому лучше со своими страхами бороться заранее

**Comment by rustho** [comment]
окей, только если не критично может я не буду исправлять здесь?, куча муторной работы просто ): и скрипт не напишешь, ибо может попасться какой-нибудь :hover и всё ):
