### ISSUE TITLE
Странное поведение аватарки пользователя во время переключения checkbox'a

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFSD-2UI#19]
Во время переключения чекбокса что-то странное происходит с аватаркой
1. До клика
![image](https://user-images.githubusercontent.com/26929933/32208943-5079e0c0-be38-11e7-9b4d-069ca843fe61.png)
2. Во время переключения
![th2m1_croper_ru](https://user-images.githubusercontent.com/26929933/32209015-a645d86a-be38-11e7-9ee9-9fc9d8293622.png)
3. После клика
![image](https://user-images.githubusercontent.com/26929933/32209008-9a6035b8-be38-11e7-8e86-ca168f61cd4a.png)

**Comment by rustho** [comment]
Я вообще хз как и почему это происходит, пытался найти причину но не нашел

**Comment by Zarwlar** [comment]
Но это же не нормально, нужно исправлять)

**Comment by rustho** [comment]
@Zarwlar А можешь подсказать хотя бы в какой стороне может баг быть? Я тыкался дня 2, никакой взаимосвязи не нашел

**Comment by Zarwlar** [comment]
Пофиксил? В чём была проблема?)

**Comment by rustho** [comment]
@Zarwlar Там у картинок позиционирование было абсолютное, ну и они видимо в резонанс с тоглами и входили (:
