### ISSUE TITLE
Непонятки с вёрсткой

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFSD-2UI#2]
Либо мы что-то неправильно запускаем, либо вёрстка абсолютно не сходится с макетом

![default](https://user-images.githubusercontent.com/26929933/29811516-f756afe6-8ccd-11e7-9c6a-1ce66126a8ec.png)

**Comment by rustho** [comment]
оу, ну это просто резиновость сыграла свою роль (: я чуть позже задам фикс значение этой гадости (:

**Comment by rustho** [comment]
Вроде поправил, должно норм работать

**Comment by Zarwlar** [comment]
Мы всё равно не можем запустить твой проект. Попробуй сам скачай и запусти, проследовав инструкциям из README

**Comment by Burize** [comment]
Сделай, чтобы его можно было запустить через dev-server. 
По поводу самой верстки. Вообще должно быть точь-точь по макету (допускается небольшие отклонения в позиционировании). Из конкретных недочетов:

-  Текст в блоках не должен прижиматься к одной из сторон (как в error у инпутов и у кнопок и еще где то скорее сего);
-  Должен быть убран дефолтный outline (слайдер и стрелочная кнопка);
-  Посмотри все шрифты еще раз. Залей макет на (https://assets.adobe.com/) он хорошо их распознает;
- Желательно, чтобы при сборке картинки и шрифты собирались в отдельные (image и fonts например). Сейчас в папке docs все вперемешку;
- При клике на toggle картинки у User Profile ненадолго становятся квадратными;
- Ну и не работает карта и у видео отображается только ползунок.

**Comment by rustho** [comment]
Карта очень странный предмет, я хз почему, но она то работает, то нет - это скорее всего ошибочки где-то на стороне гугла
Шрифт поменял на лато обычный, вроде всё тоже самое, ассетс показывает лато
насчет кликов вообще хз из-за чего, но судя по ним, это из-за рипл эффекта, хотя при тогле нет рипл эффекта
