### ISSUE TITLE
Кривой БЭМ

### ISSUE THREAD

**Issue by Znack** [rustho/TaskFSD-2UI#22]
Жутко кривой БЭМ. Где-то есть блоки и элементы, где-то нет, где-то классы вообще миксинами передаются, хотя это запрещено стандартами

**Comment by rustho** [comment]
не нашел в стандартах пункт насчет передачи классов миксинами

**Comment by Burize** [comment]
нельзя обращаться по тегам

![2018-01-09 17 13 28](https://user-images.githubusercontent.com/22253666/34715882-bdb4a972-f560-11e7-82ea-ad72c5da44a7.png)

**Comment by Burize** [comment]
совсем не по БЭМ ... 

![2018-01-09 17 16 35](https://user-images.githubusercontent.com/22253666/34715938-e9aed7e6-f560-11e7-9b2f-d177c97d804e.png)

**Comment by Burize** [comment]
https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_7mb9j/

`не нашел в стандартах пункт насчет передачи классов миксинами` - там подробно описан пример.

**Comment by rustho** [comment]
тут доделал
