### ISSUE TITLE
Сделать абстракцию для всех блоков в скриптах

### ISSUE THREAD

**Issue by Znack** [rustho/TaskFSD-2UI#23]
В скриптах на каждый блок лучше явно создавать класс, на кажлдое примнение блока в верстке нужно создавать инстанс класса и туда сохранять в this.$block корневой элемент блока, дальше все элементы через this.$block находить

**Comment by Maksimus-Prime** [comment]
"на каждое применение блока в верстке нужно создавать инстанс класса". Для чего мы это делали? Для того чтобы очередной инстанс класса инкапсулировал в себе всю работу с DOM, с обработчиками событий именно для этого очередного блока, чтобы других это ни коем образом не касалось. у тебя же сейчас инстанс создается только для одного блока, это нужно исправить
