### ISSUE TITLE
Названия блоков

### ISSUE THREAD

**Issue by Maksimus-Prime** [rustho/TaskFSD-2UI#25]
1. Что за приставка ui в каждом блоке? Зачем она нужна?
![2018-01-13 14-09-51](https://user-images.githubusercontent.com/27883524/34903783-89a523ec-f86b-11e7-8a2f-d5ad808edcaa.png)
2. Сейчас у тебя у папки в которой лежит блок одно имя, у блока другое, лучше все назвать одним именем, т.е. если у тебя блок toggles, то папка должна называться toggles. Нужно придерживаться единого код стайла, иначе когда будешь импортить свой компонент нужно будет постоянно смотреть какие там пути и как что называется

**Comment by rustho** [comment]
1 - User Interface, все классы в jquey-ui таким образом обзываются, начиная с ui-button. Да и в целом понятно же что за блок сразу же, не абстрактный тогл, а тот что на ui макете представлен. Остальные префиксы идут из вендоровских скриптов и прочего.
2. Да, глупо как-то вышло, даже не замечал -> поменял

**Comment by Maksimus-Prime** [comment]
Лучше убрать этот префикс, он не несет никакой важной семантики, ты же и так работаешь с ui компонентами, ты собираешь ui используя эти компоненты, поэтому здесь это избыточно)

**Comment by rustho** [comment]
Убрал префикс, в принципе да, так проще, сразу понимаешь что где находится.

**Comment by Maksimus-Prime** [comment]
Хорошо, а почему ты в блоке map везде префикс js добавил?

**Comment by rustho** [comment]
но название блока же js-map. эт немного легаси

**Comment by Maksimus-Prime** [comment]
Так, давай сразу, если тебе оставляют ишьюс, то ты должен исправить максимум, прошерстить весь проект(ы)

**Comment by Maksimus-Prime** [comment]
Сейчас уже лучше) Ты работаешь в vs code? Если нет, то переходи, там очень много крутых расширений помогающих в работе, если стоит то ставь себе расширение
![2018-03-16 17-48-10](https://user-images.githubusercontent.com/27883524/37516880-37f48332-2942-11e8-8436-a05aad71481e.png)
И опять же связано с кодстайлом (конвенцией именования если хочешь)
![2018-03-16 17-51-37](https://user-images.githubusercontent.com/27883524/37517064-df46d752-2942-11e8-88f3-1c62d186b2fe.png)
Ты начал уже начал отделять слова _ (standard_button, arrow_button, tick_box), то продолжай так же и с donutchart, progressBar:
donut**_**chart, progress**_**bar

**Comment by rustho** [comment]
окей, слушай @Maksimus-Prime , а чет у него странные настройки, либо я не разобрался... 
Ему не нравится "Lorem ... ", там же где-то должно более-менее логично это в игнор ставиться?

**Comment by Maksimus-Prime** [comment]
забей на lorem..., там вроде как латиница, поэтому и подчеркивает

**Comment by rustho** [comment]
Насчет lorem, удобно когда в списке проблем видишь все несостыковки, а так большая часть это латиница, я не нашел где это можно поправить, поэтому спрашиваю (: 
Да, насчет блоков верно подмечено, всё исправил. если вдруг где-то не исправил - не заметил (:

**Comment by Maksimus-Prime** [comment]
Во, сейчас уже лучше
а в первом макете есть те же косяки?

**Comment by rustho** [comment]
Ну... уже нет (:
