### ISSUE TITLE
Модификаторы?

### ISSUE THREAD

**Issue by Maksimus-Prime** [rustho/TaskFSD-2UI#26]
-fixwidth600, -flexCenter, line - Что это за сущности по БЭМу?
![2018-01-30 15-07-34](https://user-images.githubusercontent.com/27883524/35554788-87b44718-05cf-11e8-8594-131781d42394.png)

**Comment by rustho** [comment]
Они не особо по БЭМу... Сущности для удобства эти больше, модификаторы для блоков, чтобы не париться, особенно для адаптива этой ui дизайна (не знаю зачем сделал, но там требовался адаптив и я чет решил что для ui страницы надо сделать адаптив и усё).  
Стоит их убрать и сделать норм классы?

**Comment by Maksimus-Prime** [comment]
Не должно быть такого "не особо по БЭМу", есть конкретное требование в стандартах - Верстаем всегда по БЭМу, архитектура верстки должна быть компонентной.
