### ISSUE TITLE
px to rem

### ISSUE THREAD

**Issue by Maksimus-Prime** [rustho/TaskFSD-2UI#27]
В стандартах есть ряд пунктов которые ты пропустил мимо
!Пытаться по максимуму делать сайт резиновым (ставьте ширину в процентах и выставляйте max-width, min-width) - прибегайте к фиксированной ширине элемента только если по макету от этого никак не уйти
!На элементах без специфичных требований (не фиксированные пиксели и не относительно области экрана) использовать rem
Да и требование у тебя к заданию чтобы был адаптивным сайт, этого сейчас нет :(

**Comment by rustho** [comment]
везде рем и % (:

**Comment by Maksimus-Prime** [comment]
У тебя не возникал вопрос как правильно задавать относительные размеры чтобы все адекватно  адаптировалось? где лучше использовать %, где rem, а где вообще лучше задать фиксированное значение?

**Comment by rustho** [comment]
Ну фиксы нужны для фиксированной штуки, например очень хорошо подходит для бордер-радиуса
% - использовать при резиновости элементов, например какая-нибудь красивая шапка, которая растягивается на 80% ширины
ремы - для адаптива, чтобы можно было в медиа квери поменять один элемент и всё поехало поехало

**Comment by Maksimus-Prime** [comment]
я имел в виду такой вопрос: в какой относительной размерности задавать margin, padding, width, height, font-size? задать padding в rem или в %, а может быть вообще фиксированные? такие вопросы возникали?

**Comment by rustho** [comment]
а... ну там не всё так однозначно просто... 
в зависимости от блока, где-то лучше у блока длину- ширину фиксированную, где-то наоборот. тоже самое с паддингами и марджинами... 
фонт-сайз лучше всегда в ремах, % - это те же em, только переведенные в проценты... 
паддинги вроде старался делать в процентах, марджины все в ремы перевел, т.к. более точно хотел сделать блоки

**Comment by Maksimus-Prime** [comment]
А почему решил задавать padding в процентах, а margin в ремах? Там можно и так и так повторить блок, вопрос лишь в том как это будет себя вести при увеличении размера шрифта и ширины страницы/элемента

**Comment by rustho** [comment]
да в целом да, без разницы в чем ставить, это да
если в процентах то будет растягиваться от размеров окна
если в ремах то от изменения шрифта
ну паддинг внутри блоков чаще всего был, и там проще % посчитать относительно блока
А марджины были в основном между блоков и сложнее было считать размер относительно всего окна, поэтому решил в ремах -> стабильней (:

**Comment by Maksimus-Prime** [comment]
В общем тема с padding, в процентах или в rem, довольно неоднозначная и по большей части зависит от конкретной ситуации, но стоит отдавать предпочтение rem
А вот margin это обычно %, auto, но опять же зависит от ситуации
