### ISSUE TITLE
Перенести цвета в файл

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFSD-2UI#28]

**Comment by rustho** [comment]
Можно по-подробней?

**Comment by rustho** [comment]
Вот так, норм? если норм то закрываю

**Comment by Zarwlar** [comment]
Да, но можешь плз с разных сторон от знака = поставить пробелы

**Comment by rustho** [comment]
Да понимаю, а как их лучше вообще назвать, у меня 7 оттенков серого

**Comment by Zarwlar** [comment]
Как самый просто вариант gray-1, gray-2 и т.д., но имена не должны совпадать со стандартными именами CSS. Ещё можешь оставить имена такими же, но добавить префикс $, т.е. будет не gray, а $gray, например

**Comment by rustho** [comment]
Сделал вариант с $, надеюсь дизайнеры не часто извращаются добавляя тысячи оттенков в дизайн...
