### ISSUE TITLE
Настроить редактор и убрать лишние whitespace

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFSD-2UI#30]

**Comment by rustho** [comment]
Вот так норм?

**Comment by Zarwlar** [comment]
Лучше, но всё равно есть файлы с лишними whitepsace и двойными пробелами

**Comment by rustho** [comment]
Лишние whitespace - это какие? tralling spaces вроде все убрал...

**Comment by Zarwlar** [comment]
21 24 строки
![image](https://user-images.githubusercontent.com/26929933/38012955-92669248-328d-11e8-9337-85e69faaa7e4.png)

**Comment by Zarwlar** [comment]
И кстати, что за console.log('ok')?

**Comment by rustho** [comment]
да, я чет затупил, я проверил все pug, а вот стили и js не просмотрел
Лол, щас уберу, я пытался выловить баг с картами (:

**Comment by rustho** [comment]
в этом макете должно быть всё

**Comment by Geksanit** [comment]
закрывай ишью
