### ISSUE TITLE
Избавиться от каскада в стилях

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFSD-2UI#32]

**Comment by rustho** [comment]
Плиз скинь статью или что-то где показано почему это плохо, искал, и ничего не нашел

**Comment by Zarwlar** [comment]
https://ru.bem.info/methodology/quick-start/

**Comment by rustho** [comment]
Использовать миксы вместо каскада? Ты это имел в виду? 
а почему плохо использовать каскад?

**Comment by Zarwlar** [comment]
Нет, прочти внимание про то, какая иерархическая структура селекторов должна быть в БЭМ и почему именно такая, и почему плохо использовать каскад

**Comment by rustho** [comment]
так, немного проясним, когда я говорю про каскад я имею в виду вложенность селекторов... мы про одно говорим?
в БЭМе можно( но осторожно) вложенности мутить, но обязательно соблюдать инкапсуляцию. Следуя из этого я могу добавить марджины или спозиционировать блок, вложенным селектором
`.form .button{
position:absolute;
top:10px;
}` типо такого? 
Или всё таки мы должны отказаться от этого в пользу миксов? 
`<button class="button form__button"></button>` типо такого?

**Comment by Zarwlar** [comment]
Да, мы об одном и том же.
Второй вариант не очень хорош (он приемлем), но первый ещё хуже) В идеале можешь поискать ещё варианты касательно позиционирования одной БЭМ-сущности внутри другой

**Comment by rustho** [comment]
Каскад везде убрал, кроме случаев переопределения вендорных плагинов, календарь и слайдер например
