### ISSUE TITLE
Шрифты на прямоугольной кнопке не совпадают со шрифтами в макете

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFSD-2UI#35]

**Comment by rustho** [comment]
plz screen, не понял о чем ты

**Comment by Zarwlar** [comment]
![image](https://user-images.githubusercontent.com/26929933/35716536-1caef97e-080c-11e8-9bb4-4d3367e3c385.png)

**Comment by rustho** [comment]
сделано, не помню когда ещё, давно поправил...
