### ISSUE TITLE
Размер шрифтов в заголовке не совпадает с размером шрифтов в макете

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFSD-2UI#36]

**Comment by rustho** [comment]
И вот здесь скрин пожалуйста, совмещал с макетом, и в целом фотошоп показывает что всё что надо

**Comment by Zarwlar** [comment]
![image](https://user-images.githubusercontent.com/26929933/35716554-35a716e6-080c-11e8-9dc4-ce44b55523e4.png)

**Comment by rustho** [comment]
Там кастомная длина отступа между буквами, жостка очень, часто так дизайнеры издеваются?

**Comment by Zarwlar** [comment]
Если совсем не получается подогнать шрифты, то попробуй сделать приблизительно похожими, и когда посчитаешь, что больше некуда - закрывай ишус

**Comment by rustho** [comment]
![image](https://user-images.githubusercontent.com/26579566/36428335-3c1cf174-1682-11e8-8814-0ebd315697d0.png)
Вот так выглядит последний вариант

**Comment by Zarwlar** [comment]
:+1:
