### ISSUE TITLE
Предусмотреть длинные названия в UserProfile

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFSD-2UI#43]
![image](https://user-images.githubusercontent.com/26929933/35612404-4539b630-069b-11e8-8de8-8372d89676e0.png)

**Comment by rustho** [comment]
Слушай, а что значит предусмотреть длинные названия? 
насколько они должны быть длинные? 
Я убрал фиксированную длину и высоту, но если мы задаем длину родителя в процентах(здесь я говорю о блоке в котором находятся оба UserProfile), то почему то портрет становится овалом... 
Если убираю там длину в процентах всё великолепно работает

**Comment by Zarwlar** [comment]
Если влазит Константин Константинович Константинопольский, то ок
