### ISSUE TITLE
Предусмотреть большое количество текста в news

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFSD-2UI#44]
![image](https://user-images.githubusercontent.com/26929933/35612436-5ea88baa-069b-11e8-9fb0-3466be6c5beb.png)

**Comment by rustho** [comment]
У меня траблы с news и events, сейчас блоки захардкожены (длина в % +  высота в rem), из-за того что флексы растягивают блок и он становится немного больше чем на макете (10% примерно), но если убрать родительский блок который задает размеры (которые захардкожены) то всё тянется и вообще выглядит прекрасно

**Comment by rustho** [comment]
Если всё норм, то я закрываю?

**Comment by Zarwlar** [comment]
А что изменилось?

**Comment by rustho** [comment]
Я загнал их в блоки специально, т.к. иначе они разбежались и стали больше чем в макете

**Comment by Zarwlar** [comment]
А можешь скриншот скинуть, что теперь происходит при большом количестве текста?
