### ISSUE TITLE
Предусмотреть большое количество текста в events

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFSD-2UI#45]
![image](https://user-images.githubusercontent.com/26929933/35612470-75c4243e-069b-11e8-988f-8c696716636b.png)

**Comment by Maksimus-Prime** [comment]
А ты точно исправил?
![2018-03-16 17-34-37](https://user-images.githubusercontent.com/27883524/37516342-58b10a2a-2940-11e8-92aa-45c9628dfbf3.png)
Текст который вставлял: Lorem ipsum dolor sit amet, consasdfsadfasfasfadsfasdfasdf sadfasdfasdfasdfasd asdfasdf asdf asdfasdfsafsadfasdfasfasdfsadfasdfaasdfasdfasdfasdfasdfasdfsd asdfasdfectetur adipiscing elit.
Понятно, что вряд ли такое слово есть, но ты должен быть ко всему

**Comment by rustho** [comment]
![image](https://user-images.githubusercontent.com/26579566/37531059-a5435438-296d-11e8-8260-2afe3f7107f9.png)
Еще раз повторю, на данном макете они находятся в фиксированном блоке, т.к. немного разъезжаются (просто в размере увеличиваются) 
![image](https://user-images.githubusercontent.com/26579566/37531139-dd17972a-296d-11e8-984c-ac45c93af57d.png)
1 - ый какой размер блока должен быть, а второй какой он становится когда разъезжается...

**Comment by Maksimus-Prime** [comment]
Не пойму, а почему если он ограничен по ширине, то не растягивается по высоте? почему бы не переносить этот текст?

**Comment by rustho** [comment]
ну потому что твое слово "asdfasdfsafsadfasdfasfasdfsadfasdfaasdfasdfasdfasdfasdfasdfsd" слишком длинное (: 
не ну если это прям необходимо, введение 61-символьного слова, то можно замутить word-break, но он режет и обычные слова. 
Вот смотри -> красный блок - ничего не изменял, зеленый блок - поставил ворд- брик.
![image](https://user-images.githubusercontent.com/26579566/37554956-a5acbb3a-2a12-11e8-9aef-8511b8c5f4ff.png)

**Comment by Maksimus-Prime** [comment]
А вот теперь засунь 61 символьное слово в оранжевый блок, посмотрим как его разнесет :) Понимаешь, вот в чем дело, может быть всякое, представь что там человек где-то пропустил пробелы или они каким-то образом от тебя не зависящим слиплись, ты должен быть готов ко всему, поэтому word-break норм тема

**Comment by rustho** [comment]
могу конечно поставить word-break, просто он прям всё очень не красиво режет...

**Comment by rustho** [comment]
Вроде так норм

**Comment by Maksimus-Prime** [comment]
Длинный текст может быть и в заголовке и в описании

**Comment by rustho** [comment]
Насчет заголовка и описания согласен, но дата будет выглядеть печальной очень 
![image](https://user-images.githubusercontent.com/26579566/37706953-df05da64-2d33-11e8-857a-0f18796f6184.png)
тут вопрос всё таки стоит в дизайне уже, что главное для дизайна этой юишки, чтобы она была четкой квадратной формы как на юи, или могла расползаться по вертикали и горизонтали...

**Comment by rustho** [comment]
Тут всё четко? Закрываю?

**Comment by Maksimus-Prime** [comment]
Почти. Добавь еще в &__date word-break и все будет как надо :)
Твоя задача как фронтендера адаптировать этот ui компонент к различного рода ситуациям: всякое может быть, может придти мало текста, может придти много текста, а может он вообще не прийти (представь бэк крашнулся) и ты отвечаешь за то, чтобы компонент по-максимуму выглядел адекватно на странице
"или могла расползаться по вертикали и горизонтали...", чаще всего вопрос стоит о ширине экрана , и задается какая-то относительная/фиксированная ширина, а вот высота имеет динамический характер

**Comment by rustho** [comment]
Да там просто так нельзя было добавить word-break, разрезалось название месяца и выглядит не очень, как на скринах выше, щас всё норм вроде
Насчет разьяснения высоты и ширины, спасибо, всегда не мог понять за чем нужно следить в первую очередь

**Comment by Maksimus-Prime** [comment]
Можно закрывать
