### ISSUE TITLE
Убрать горизонтальный скролл

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFSD-2UI#48]
Не знаю, что именно, но что-то в твоём макете влияет на возникновение горизонтального скролла. От этого нужно избавиться
![image](https://user-images.githubusercontent.com/26929933/35612559-bdec22c0-069b-11e8-9c5e-f0b9f9910f2e.png)

**Comment by rustho** [comment]
вроде исчез он, понятия не имею что с ним не так (:
