### ISSUE TITLE
Position: relative

### ISSUE THREAD

**Issue by Zarwlar** [rustho/TaskFSD-2UI#55]
У map__adress задан position relative и top одновременно. Это нужно исправить

**Comment by Zarwlar** [comment]
.nav .tab-selected сюда же

**Comment by rustho** [comment]
А что не так? Чем черевато? 
вроде норм тема с относительным позиционированием, нет?

**Comment by Zarwlar** [comment]
Это чревато неочевидным поведением блока при переиспользовании. Пунктик есть в стандартах

**Comment by rustho** [comment]
Всё, увидел
