### ISSUE TITLE
Все include, импорты делать в начале файла

### ISSUE THREAD

**Issue by Maksimus-Prime** [rustho/TaskFSD-2UI#61]
![2018-03-16 18-22-32](https://user-images.githubusercontent.com/27883524/37518258-07e1dd70-2947-11e8-9286-bb1d9b81b184.png)
И лучше разделять include и дальнейший код пробелом, увеличивает читабельность по сравнению с вот этим подходом
![2018-03-16 18-15-04](https://user-images.githubusercontent.com/27883524/37518002-fc6f9226-2945-11e8-939d-acecdb0dde83.png)

**Comment by Maksimus-Prime** [comment]
Теперь смотри, где-то у тебя разделены пустой строкой include, данные и сама верстка, а где-то все слиплось, нужно это поправить
![2018-03-20 19-26-44](https://user-images.githubusercontent.com/27883524/37654503-e5ed3eea-2c74-11e8-8d5f-2956e5bdf722.png)

**Comment by rustho** [comment]
Да, доделал, странно что так вышло, скорее всего не сохранил и запушил

**Comment by Maksimus-Prime** [comment]
Так-с, давай еще вот здесь придерживаться этой конвенции
![2018-03-21 11-37-25](https://user-images.githubusercontent.com/27883524/37694765-4035cdfe-2cfc-11e8-8468-b471e10d1dd1.png)
Ты можешь поискать по проекту все конструкции include и отделить их пустой строкой, в vs code можно вот так
![include](https://user-images.githubusercontent.com/27883524/37694809-9a552adc-2cfc-11e8-8963-79bc12245bc8.gif)
