### ISSUE TITLE
toggles плывет при уменьшении экрана

### ISSUE THREAD

**Issue by Maksimus-Prime** [rustho/TaskFSD-2UI#63]
![toggles_bug](https://user-images.githubusercontent.com/27883524/37654251-0c2ad596-2c74-11e8-96a5-70a9e4bd09d9.gif)

**Comment by rustho** [comment]
через что записываешь гифки с экрана?

**Comment by Maksimus-Prime** [comment]
Peek :)
![2018-03-21 11-13-08](https://user-images.githubusercontent.com/27883524/37694330-e425a3de-2cf8-11e8-8ae8-1a2fbd67863d.png)
