### ISSUE TITLE
Убрать горизонтальный скролл

### ISSUE THREAD

**Issue by Maksimus-Prime** [rustho/TaskFSD-2UI#64]

**Comment by rustho** [comment]
У меня всё норм, без скролла...
при каком разрешении смотришь?

**Comment by rustho** [comment]
вот так он не появляется до 1040px, в поисках того что его заставляет появляться...

**Comment by rustho** [comment]
![image](https://user-images.githubusercontent.com/26579566/37708716-48a4fd78-2d3a-11e8-9375-3a58719e35c0.png)
Вроде это оно, чет я не уверен что смогу вылечить, но попытаюсь

**Comment by rustho** [comment]
Хм, крч нашел я почему появляется скролл... Риппл эффект его создает... Искать другой вендор или оставить всё как есть?

**Comment by Maksimus-Prime** [comment]
У меня он сразу же на странице, без скроллов
![2018-03-22 16-22-11](https://user-images.githubusercontent.com/27883524/37761803-3bb90e20-2ded-11e8-88b4-c0168072fd41.png)
А ты гуглил как люди решают вопрос с скроллом?

**Comment by rustho** [comment]
Поискал всякие решения, вроде выглядит это больше как трюк и костыль 
`overflow-x: hidden;`

**Comment by Maksimus-Prime** [comment]
Нет, на самом деле это стандартное решение :)
