### ISSUE TITLE
Не соблюадется правило стандартов про префиксы классов при селекторах из js

### ISSUE THREAD

**Issue by Znack** [rustho/TaskFSD-2UI#8]

**Comment by Maksimus-Prime** [comment]
Можешь расписать здесь где и что ты исправил?)

**Comment by rustho** [comment]
ух... если кратко то у меня вообще это правило не соблюдалось. 
ui-calendar -> js-ui-calendar
ui-donutchart -> js-ui-donutchart
ui-map -> js-ui-map
ui-slider -> js-ui-slider
video -> js-video

**Comment by Maksimus-Prime** [comment]
А ты так и не понял как это работает, вот смотри, у тебя есть блок, есть название блока - .block, так вот если ты его ищешь в своих js файлах тебе нужно добавить ему еще один класс с префиксом js: .block.js-block, и в js ты работаешь с этим блоком только через этот класс с префиксом)
В стандартах все подробно написано, такое ощущение что ты вообще их не читал)
https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_78v67/
Так делать не надо
![2018-01-22 15-55-20](https://user-images.githubusercontent.com/27883524/35212434-afe57188-ff8c-11e7-93bb-d62466a62047.png)

**Comment by rustho** [comment]
а, ок, читал, но не исправил

**Comment by rustho** [comment]
доделал
